Updated Routes
BingeWave-Libraries/react-api pull request #6
Opened 2022-07-23 17:19 UTC by Yeshuwa

Updated route assignment!

2022-07-23 17:55 UTC, ProdigyView requested changes
So I didn't go through the entire thing but a lot of the bugs in here is that you are forgetting both parameters and to replace them in the routes. For example:

`/events/{event_id}/tickets/{ticket_id}/refund",

This route has two variables that need replacing, event_id and ticket_id . So your method should look like the following:

```
public static refundTicket(event_id : string, ticket_id : string, data : object, query? : object | null, options? : object | null) {
    let route = this.routeCreateGroup.route.replaceAll('{id}',event_id);
    route = route.replaceAll('{ticket_id}',ticket_id);

}
```

Before sure to review the code and check for all of those carefully.

2022-07-23 17:55 UTC, ProdigyView commented on src/Events/Events.ts
> +    private static
This is a bug right here. The code will not compile, please fix.

2022-07-23 17:55 UTC, ProdigyView commented on src/Events/Events.ts
> +    public static updateGroup(event_id : string, data : object, query? : object | null, options? : object | null) {
There should be another parameter, group_id. And the parameter should be replaced in the route as well.

2022-07-23 17:55 UTC, ProdigyView commented on src/Events/Events.ts
> +    public static listGroup(event_id : string,  query? : object | null, options? : object | null) {
Again, the group_id should be a parameter, and also replaced in the route.

2022-07-23 17:55 UTC, ProdigyView commented on src/Events/Events.ts
> +    public static ViewGroup(event_id : string,  query? : object | null, options? : object | null) {
Same here the group_id should be a parameter, and replaced in the route.

2022-07-23 17:55 UTC, ProdigyView commented on src/Events/Events.ts
> +    public static deleteGroup(data : object, query? : object | null, options? : object | null) {
You are forgetting to pass the event_id and group id, and replacing those both in the route.

2022-07-23 17:55 UTC, ProdigyView commented on src/Events/Events.ts
> +    public static registerAttendee(data : object, query? : object | null, options? : object | null) {
The event id in the route is missing

2022-07-23 17:55 UTC, ProdigyView commented on src/Events/Events.ts
> +        route : "/events/{event_id}/hasTicket/{account_id",
account id is missing ending bracket

2022-07-23 17:55 UTC, ProdigyView commented on src/Events/Events.ts
> +    public static hasTicket(event_id : string,  query? : object | null, options? : object | null) {
The account id is required in the parameter, and has to be replaced in the route.

2022-07-23 17:55 UTC, ProdigyView commented on src/Events/Events.ts
> +    public static viewTicket(event_id : string,  query? : object | null, options? : object | null) {
The ticket_id is required as the parameter, and must be replaced in the route.

2022-07-23 17:55 UTC, ProdigyView commented on src/Events/Events.ts
> +    public static refundTicket(data : object, query? : object | null, options? : object | null) {
The event_id and ticket_id is missing the parameters, and must be replaced.

2022-08-02 10:57 UTC, ProdigyView requested changes
The changes that we talked about have not been done. What happened?

2022-08-02 10:57 UTC, ProdigyView commented on src/Events/Events.ts
> +    private static
@Yeshuwa This bug has still not been addressed.

2022-08-02 10:57 UTC, ProdigyView commented on src/Events/Events.ts
> +        route : "/events/{event_id}/hasTicket/{account_id",
@Yeshuwa Still need to address this issue.

2022-08-02 10:57 UTC, ProdigyView commented on src/Events/Events.ts
> +    public static updateGroup(event_id : string, data : object, query? : object | null, options? : object | null) {
How is this resolve? group_id is still missing.

2022-08-02 10:57 UTC, ProdigyView commented on src/Events/Events.ts
> +    public static viewTicket(event_id : string,  query? : object | null, options? : object | null) {
Same here

2022-08-02 17:13 UTC, Yeshuwa commented
Maybe I missed some of them, but all the ones that you assigned through
GitHub and left a message for me for I fixed. I’ll go back and finish them
today along with the react assignment.

On Tue, Aug 2, 2022 at 3:57 AM Devin Dixon ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> The changes that we talked about have not been done. What happened?
> ------------------------------
>
> In src/Events/Events.ts
> <https://github.com/BingeWave-Libraries/react-api/pull/6#discussion_r935412914>
> :
>
> > @@ -3,6 +3,145 @@ import Requests from "../Util/Requests";
>  import RequestTypes from "../Util/RequestTypes";
>
>  class Events {
> +    private static routeDisconnectUser: Route = {
> +        route : "/events/{id}/disconnectUser",
> +        method : RequestTypes.POST
> +    };
> +    private static routeConnectUser: Route = {
> +        route : "/events/{id}/connectUser",
> +        method : RequestTypes.POST
> +    };
> +    private static routeAddUserToAudience: Route = {
> +        route : "/events/{id}/removeUserFromStage",
> +        method : RequestTypes.POST
> +    };
> +    private static
>
> @Yeshuwa <https://github.com/Yeshuwa> This bug has still not been
> addressed.
> ------------------------------
>
> In src/Events/Events.ts
> <https://github.com/BingeWave-Libraries/react-api/pull/6#discussion_r935414619>
> :
>
> > @@ -312,6 +451,144 @@ class Events {
>          return Requests.post(route, data, query, options);
>      }
>
> +    public static createGroup (event_id : string, data : object,query? : object | null,options? : object |null  ) {
> +        let route = this.routeCreateGroup.route.replaceAll('{id}',event_id);
> +
> +        return Requests.post(route,data,query,options);
> +    }
> +    public static updateGroup(event_id : string, data : object, query? : object | null, options? : object | null) {
>
> How is this resolve? group_id is still missing.
> ------------------------------
>
> In src/Events/Events.ts
> <https://github.com/BingeWave-Libraries/react-api/pull/6#discussion_r935413406>
> :
>
> > +        method : RequestTypes.POST
> +    }
> +    private static routeAddUser: Route = {
> +        route : "/events/{id}/addUserToAttendees",
> +        method : RequestTypes.POST
> +    }
> +    private static routeRefundTicket: Route = {
> +        route : "/events/{event_id}/tickets/{ticket_id}/refund",
> +        method : RequestTypes.POST
> +    }
> +    private static routeViewTicket: Route = {
> +        route : "/events/{event_id}/tickets/{ticket_id}",
> +        method : RequestTypes.GET
> +    }
> +    private static routeHasTicket: Route = {
> +        route : "/events/{event_id}/hasTicket/{account_id",
>
> @Yeshuwa <https://github.com/Yeshuwa> Still need to address this issue.
> ------------------------------
>
> In src/Events/Events.ts
> <https://github.com/BingeWave-Libraries/react-api/pull/6#discussion_r935419710>
> :
>
> > +        return Requests.post(this.routeDeleteGroup.route, data, query, options);
> +    }
> +    public static registerAttendee(data : object, query? : object | null, options? : object | null) {
> +        return Requests.post(this.routeRegisterAttendee.route, data, query, options);
> +    }
> +    public static listTickets(event_id : string,  query? : object | null, options? : object | null) {
> +        let route = this.routeListTickets.route.replaceAll('{id}', event_id);
> +
> +        return Requests.get(route, query, options);
> +    }
> +    public static hasTicket(event_id : string,  query? : object | null, options? : object | null) {
> +        let route = this.routeHasTicket.route.replaceAll('{id}', event_id);
> +
> +        return Requests.get(route, query, options);
> +    }
> +    public static viewTicket(event_id : string,  query? : object | null, options? : object | null) {
>
> Same here
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BingeWave-Libraries/react-api/pull/6#pullrequestreview-1058557022>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUS7NFZ7DCYX5FPXU4RM34DVXD5LFANCNFSM54OJEXSQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-30 10:37 UTC, merged